// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbobjgvctghdzovnjzrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhib2JqZ3ZjdGdoZHpvdm5qenJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzU2MTIsImV4cCI6MjA3NDU1MTYxMn0.uPRZPKGR2q001CQtLAkDowyzB3Ej4dyKdws921VxQ9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});